added notificationsScreen
himanshusharma89/relic_bazaar pull request #184
Opened 2021-04-09 05:09 UTC by anotherwebguy

### Related Issue
- Fixes #38 

### Proposed Changes
Added Notifications Toggle Screen

### Checklist
- [x] Tested
- [x] No Conflicts
- [x] Change In Code
- [x] Follows linting rules

### Screenshots

![image](https://user-images.githubusercontent.com/66346161/114131206-d2868800-991f-11eb-971a-711e482278b0.png)

2021-04-10 17:10 UTC, himanshusharma89 requested changes

2021-04-10 17:10 UTC, himanshusharma89 commented on lib/views/profile/settings/notifications_toggle.dart
> +                  Row(
Instead of Row use ListView here with leading and trailing properties

2021-04-10 17:10 UTC, himanshusharma89 commented on lib/views/profile/settings/notifications_toggle.dart
> +          Center(
Use column to align the content

2021-04-10 17:16 UTC, anotherwebguy commented on lib/views/profile/settings/notifications_toggle.dart
> +          Center(
Yeah i'll do it

2021-04-10 17:22 UTC, himanshusharma89 commented on lib/views/profile/settings/notifications_toggle.dart
> +                  Row(
ListTile* @anotherwebguy

2021-04-11 06:17 UTC, anotherwebguy commented
hey @himanshusharma89 i've made the changes usked for plz review...hope u will merge it soon

2021-04-11 15:07 UTC, himanshusharma89 requested changes

2021-04-11 15:07 UTC, himanshusharma89 commented on lib/views/profile/settings/notifications_toggle.dart
> +      body: SafeArea(
SafeArea is not required since we used appBar.

2021-04-11 15:07 UTC, himanshusharma89 commented on lib/views/profile/settings/notifications_toggle.dart
> +            child: Column(
Remove this Column

2021-04-11 16:02 UTC, anotherwebguy commented
Yeah i'll do it

2021-04-12 04:22 UTC, anotherwebguy commented
i've made the requested changes...hope u'll merge it soon @himanshusharma89

2021-04-12 04:26 UTC, himanshusharma89 requested changes

2021-04-12 04:26 UTC, himanshusharma89 commented on lib/helpers/constants.dart
> +<<<<<<< HEAD
The rebasing is not done perfectly

2021-04-12 04:26 UTC, himanshusharma89 commented on lib/helpers/route_page.dart
> +<<<<<<< HEAD
Same here

2021-04-12 04:26 UTC, himanshusharma89 commented on lib/helpers/route_page.dart
> +<<<<<<< HEAD
And here

2021-04-12 04:55 UTC, anotherwebguy commented
made the changes sir @himanshusharma89

2021-04-12 12:10 UTC, merged