Fixes #230
himanshusharma89/relic_bazaar pull request #231
Opened 2021-05-08 13:35 UTC by SapinderSingh

### Related Issue
- Fixes #230

### Proposed Changes
- Created GetUserDetailsView
- Added and linked route.

### Checklist
- [X] Tested
- [X] No Conflicts
- [X] Change In Code
- [ ] Change In Documentation
- [X] Follows linting rules

### Screenshots
![signal-2021-05-08-185657](https://user-images.githubusercontent.com/29424616/117541165-33dd6c00-b030-11eb-890b-ec8e065e4cd7.jpeg)

2021-05-11 00:53 UTC, himanshusharma89 requested changes

2021-05-11 00:53 UTC, himanshusharma89 commented on lib/services/auth_service.dart
> +        Navigator.of(context).pushReplacementNamed(
As we are using StreamBuilder, Navigator won't work, try to do it main.dart using SharedPref

2021-05-12 00:57 UTC, SapinderSingh commented
https://user-images.githubusercontent.com/29424616/117902453-1be54100-b2eb-11eb-970e-8292c4d9d770.mp4

2021-05-12 04:26 UTC, himanshusharma89 approved these changes

2021-05-12 04:26 UTC, merged